AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GWMailer

  Sample SAM Template for GWMailer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

#Parameters:

Resources:
  MailAlerts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gold_watch/
      #Role: !GetAtt LambdaRoleForSES.Arn
      Policies:
        - Statement:
          - Sid: LamdbaSESPolicy
            Effect: Allow
            Action: 
              - ses:SendEmail
              - ses:SendRawEmail
              - ses:SendTemplatedEmail
            Resource: '*'
      Handler: MailAlerts.lambda_handler
      Runtime: python3.9
      Architectures: 
        - x86_64  
             
#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
