AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GoldWatch

  Sample SAM Template for GoldWatch

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            
  GetDateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: date.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetDate:
          Type: Api
          Properties:
            Path: /date
            Method: get
            
  PullCurGoldPrice:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: PullCurGoldPrice.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetDate:
          Type: Api
          Properties:
            Path: /pullcurgoldprice
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetDateApi:
    Description: "Api Gateway endpoint URL for Prod stage for GetDate function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/date/" 
  PullCurGoldPriceApi:
    Description: "Api Gateway endpoint URL for Prod stage for GetCurGoldPrice function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pullcurgoldprice/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  GetDateFunction:
    Description: "Get date lambda function ARN"
    Value: !GetAtt GetDateFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
