version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gw-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yaz0v1licauq"
s3_prefix = "gw-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaSQSManagedPolicy=\"arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole\" LambdaSESRoleName=\"lambda-ses-role\""
image_repositories = []
disable_rollback = true
