AWSTemplateFormatVersion: '2010-09-09'
Description: >
  GoldWatch

  CodeDeploy to EC2 instance template

#Metadata: 

Parameters:
  CodeDeployRolePolicy:
    Type: String
    Description: Role needed by CodeDeploy to deploy on EC2 instances
    Default: arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
    
  ExportEC2StackName:
    Type: String
    Description: The CodeDeploy Service Role Arn
    Default: gold-watch

  ExportALBStackName:
    Type: String
    Description: ALB Target Group Name
    Default: gw-alb
  
  RevCommitId:
    Description: The commit ID for the rev.
    Type: String
    Default: 85f8907a8a77223c224009dbd8513678f3c4160a

Resources: 
  GoldWatchWwwApp:
    Type: AWS::CodeDeploy::Application
    Properties: 
      ApplicationName: goldwatch_www
      ComputePlatform: Server
      Tags: 
        - Key: Name
          Value: goldwatch_www

#  CodeBuildSourceCredential:
#    Type: AWS::CodeBuild::SourceCredential
#    Properties:
#      AuthType: PERSONAL_ACCESS_TOKEN
#      ServerType: GITHUB
#      Token: "{{resolve:ssm-secure:gw-githubauthtoken:1}}"
      
            

  AllAtOnce:
    Type: AWS::CodeDeploy::DeploymentConfig
    Properties: 
      ComputePlatform: Server
      DeploymentConfigName: gw_deployconfig
      MinimumHealthyHosts: 
        Type: HOST_COUNT 
        Value: 1
      #TrafficRoutingConfig: 
      #  Type: AllAtOnce       
        
  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref GoldWatchWwwApp
      Deployment:
        Description: Deploy the GoldWatch Website.
        IgnoreApplicationStopFailures: True
        Revision:
          GitHubLocation:
            CommitId: !Ref RevCommitId 
            Repository: ohbster/GoldWatch_WWW
          RevisionType: GitHub
            
      DeploymentConfigName: !Ref AllAtOnce
      DeploymentGroupName: GoldWatchDeploymentGroup #Adding a name means you cannot make changes to this resource without deleting 
      DeploymentStyle:
        DeploymentOption: WITH_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE

      LoadBalancerInfo: 
         TargetGroupInfoList: 
           - Name: 
               Fn::ImportValue: !Sub ${ExportALBStackName}-ALBTargetGroupName
        
        
      ServiceRoleArn: 
        Fn::ImportValue: !Sub ${ExportEC2StackName}-EC2CodeDeployServiceRole
    
      
      
#Outputs: 